name: Criar diretório dev no Ubuntu

on:
  push:
    branches:
      - 1-exercício-1-diretorio-dev-front-end

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Criar diretório no servidor
        run: |
          set -e
          echo "Iniciando conexão SSH..."
          ssh -o StrictHostKeyChecking=no jaime@servidores-linux.70-71-bc-12-b3-87@cloud.shellhub.io "mkdir -p /home/jaime/dev/front-end"
          echo "Diretório /home/jaime/dev/front-end criado com sucesso!"

      - name: Configurar GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Fazer login no GitHub CLI
        run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

      - name: Criar Pull Request para a branch develop
        run: |
           gh pr create \
           --base develop \
           --head 1-exercício-1-diretorio-dev-front-end \
           --title "PR para adicionar diretório no servidor" \
           --body "Este PR adiciona o diretório /home/jaime/dev/front-end no servidor." \
           --auto-merge

      - name: Fechar a Issue
        run: |
          set -e
          echo "Fechando a issue #1..."
          gh issue close 1 --repo ${{ github.repository }}
          echo "Issue #1 fechada com sucesso."