name: Criar diretório dev no Ubuntu

on:
  push:
    branches:
      - 1-exercício-1-diretorio-dev-front-end

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Criar diretório no servidor
        run: |
          set -e
          echo "Iniciando conexão SSH..."
          ssh -o StrictHostKeyChecking=no jaime@servidores-linux.70-71-bc-12-b3-87@cloud.shellhub.io "mkdir -p /home/jaime/dev/front-end"
          echo "Diretório /home/jaime/dev/front-end criado com sucesso!"

      - name: Criar Pull Request
        id: create_pr
        run: |
          set -e
          echo "Iniciando criação do PR..."

          # Definir variáveis
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          BRANCH_HEAD="1-exercício-1-diretorio-dev-front-end"
          BRANCH_BASE="develop"
          TITLE="PR para adicionar diretório no servidor"
          BODY="Este PR adiciona o diretório /home/jaime/dev/front-end no servidor."

          echo "Variáveis:"
          echo "REPO_OWNER: $REPO_OWNER"
          echo "REPO_NAME: $REPO_NAME"
          echo "BRANCH_HEAD: $BRANCH_HEAD"
          echo "BRANCH_BASE: $BRANCH_BASE"
          echo "TITLE: $TITLE"
          echo "BODY: $BODY"

          # Criar Pull Request
          PR_RESPONSE=$(curl -s -w "%{http_code}" -o response.json -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"head\": \"$BRANCH_HEAD\",
              \"base\": \"$BRANCH_BASE\",
              \"title\": \"$TITLE\",
              \"body\": \"$BODY\"
            }" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls")

          # Verificando o código de status HTTP
          HTTP_STATUS=$(tail -n1 response.json)
          if [[ "$HTTP_STATUS" != "201" ]]; then
            echo "Erro ao criar o PR. Status code: $HTTP_STATUS"
            echo "Resposta completa: $(cat response.json)"
            exit 1
          fi

          # Extraindo o número do PR
          PR_NUMBER=$(cat response.json | jq -r .number)
          echo "Pull request criado com sucesso. Número: $PR_NUMBER"
          echo "pr_nu
